### ISSUE TITLE
AVMetadataObject 有矩形类型吗?

### ISSUE THREAD

**Issue by hccgk** [HersonIQ/IQEngUICamera#1]

**Comment by HansenCCC** [comment]
抱歉现在才看到，但是你说的矩形我可能不太理解。
                                             @[AVMetadataObjectTypeQRCode,
                                                 AVMetadataObjectTypeEAN13Code,
                                                 AVMetadataObjectTypeEAN8Code,
                                                 AVMetadataObjectTypeCode128Code,
                                                 AVMetadataObjectTypeFace
                                                 ]] 如果你说指的是这些的话，我回答是没有 。很抱歉没有给你好的建议

**Comment by hccgk** [comment]
谢谢
